import i18n, { normalizeLanguage, type AppLanguage } from "./i18n";

// Most of the original WebUI predates the i18next setup and contains literal
// English labels. Keep their translations centralized while components are
// migrated incrementally. Exact matching deliberately avoids translating
// Agent names, conversation content, file names, commands, or model output.
export const UI_TEXT_ZH: Record<string, string> = {
  "Needs You": "需要你决定",
  Topics: "协作事项",
  Overview: "概览",
  Team: "团队",
  External: "外部连接",
  Agents: "Agents",
  "Find agent…": "搜索 Agent…",
  "Search agents by name": "按名称搜索 Agent",
  "Clear agent search": "清空搜索",
  "Clear search": "清除搜索",
  "New result": "有新结果",
  "New agent": "新建 Agent",
  Settings: "设置",
  Status: "状态",
  Capacity: "容量",
  "Token usage": "Token 用量",
  Messages: "消息",
  Directory: "Agent 名录",
  Organization: "组织关系",
  Collaboration: "协作关系",
  Activity: "活动",
  Schedules: "定时任务",
  Inbox: "收件箱",
  Outbox: "发件箱",
  Identities: "外部身份",
  Conversations: "会话",
  Connections: "连接",
  Integrations: "集成",
  Runtime: "运行环境",
  Connectors: "连接器",
  Backup: "备份",
  Remote: "远程访问",
  General: "常规",
  Profile: "档案",
  Usage: "用量",
  Identity: "身份",
  Domain: "领域职责",
  Scope: "职责边界",
  Model: "模型",
  Reasoning: "推理强度",
  Sandbox: "沙箱",
  Approval: "审批策略",
  Workspace: "工作目录",
  Thread: "Thread",
  Goal: "目标",
  Artifacts: "产物",
  Attachments: "附件",
  Input: "输入",
  Result: "结果",
  Purpose: "目的",
  Completion: "完成条件",
  "Next step": "下一步",
  Limitations: "限制",
  Responsible: "负责人",
  Participants: "参与者",
  Owner: "Owner",
  Lead: "负责人",
  Member: "成员",
  Provider: "平台",
  Conversation: "会话",
  Address: "地址",
  Attempts: "尝试次数",
  Enabled: "已启用",
  Disabled: "已停用",
  Connected: "已连接",
  connected: "个已连接",
  Disconnected: "未连接",
  Active: "活跃",
  active: "活跃",
  Idle: "空闲",
  idle: "空闲",
  Working: "工作中",
  Interrupted: "已中断",
  interrupted: "已中断",
  Pending: "等待中",
  Queued: "已排队",
  Delivered: "已送达",
  Failed: "失败",
  Complete: "已完成",
  Completed: "已完成",
  Open: "打开",
  Closed: "已关闭",
  Available: "可用",
  Unavailable: "不可用",
  Unknown: "未知",
  Default: "默认",
  agents: "个 Agent",
  "need you": "需你处理",
  Optional: "可选",
  optional: "可选",
  None: "无",
  Never: "从不",
  Today: "今天",
  Yesterday: "昨天",
  Name: "名称",
  Description: "说明",
  Details: "详情",
  Configuration: "配置",
  Guidance: "行为指引",
  Role: "角色",
  Permissions: "权限",
  Credentials: "凭证",
  Secret: "密钥",
  Language: "语言",
  English: "English",
  Chinese: "简体中文",
  Save: "保存",
  Saving: "保存中",
  Saved: "已保存",
  Cancel: "取消",
  Close: "关闭",
  Create: "创建",
  Creating: "创建中",
  Edit: "编辑",
  Delete: "删除",
  Remove: "移除",
  Archive: "归档",
  Restore: "恢复",
  Add: "添加",
  Update: "更新",
  Refresh: "刷新",
  Restart: "重启",
  Continue: "继续",
  Dismiss: "忽略",
  Reply: "回复",
  Send: "发送",
  Stop: "停止",
  Submit: "提交",
  Confirm: "确认",
  Copy: "复制",
  Copied: "已复制",
  Search: "搜索",
  Filter: "筛选",
  Clear: "清除",
  Apply: "应用",
  Check: "检查",
  Import: "导入",
  Export: "导出",
  Install: "安装",
  Connect: "连接",
  Disconnect: "断开连接",
  Manage: "管理",
  View: "查看",
  Back: "返回",
  Next: "下一步",
  Previous: "上一步",
  Done: "完成",
  "Create agent": "创建 Agent",
  "Create a long-lived domain agent backed by a Codex Thread.": "创建一个由 Codex Thread 支撑的长期领域 Agent。",
  "Agent name": "Agent 名称",
  "Working directory": "工作目录",
  "The enduring subject this Agent will maintain": "这个 Agent 将长期负责的领域",
  "No agents yet.": "还没有 Agent。",
  "Select or create an agent to begin.": "选择或创建一个 Agent 开始工作。",
  "Agent settings": "Agent 设置",
  "Edit settings": "编辑设置",
  "External identities": "外部身份",
  "identities ·": "个身份 ·",
  "conversation roles ·": "个会话角色 ·",
  "External connections": "外部连接",
  "Owner decisions waiting": "等待 Owner 决定",
  "No Owner decision waiting": "没有等待 Owner 的决定",
  "No agents are working right now.": "当前没有 Agent 正在工作。",
  "Show active agents": "显示活跃 Agents",
  "Open agents": "打开 Agents",
  "open agents": "打开 Agents",
  "Overview views": "概览视图",
  "Team execution and Owner attention": "团队执行与 Owner 待处理事项",
  "Collapse sidebar": "折叠侧栏",
  "Expand sidebar": "展开侧栏",
  "Close sidebar": "关闭侧栏",
  "Needs your input": "需要你的输入",
  "Working now": "正在工作",
  "Daily activity": "每日活动",
  "Executing now": "正在执行",
  "No queued Agent work": "没有排队中的 Agent 工作",
  "No enabled connections": "没有已启用的外部连接",
  live: "实时",
  "Previous day": "前一天",
  "Next day": "后一天",
  "Activity date": "活动日期",
  "day total": "当日总计",
  "Token volume": "Token 用量",
  "same 30m axis": "使用同一 30 分钟时间轴",
  "No Turn or token activity was recorded for this day.": "当天没有记录到 Turn 或 Token 活动。",
  "How to read this": "如何阅读此图",
  "current state": "当前状态",
  clear: "正常",
  "No Owner decision waiting.": "没有等待 Owner 的决定。",
  "Runtime status": "运行状态",
  "System status": "系统状态",
  "Build information": "构建信息",
  "Data directory": "数据目录",
  "Web asset": "Web 资源",
  "Last updated": "最后更新",
  "Last error": "最近错误",
  "Last turn failed:": "上一轮执行失败：",
  "Jump to latest": "跳到最新消息",
  "Answering request": "正在回答请求",
  "Cancel answering mode": "取消回答模式",
  "Remove attachment": "移除附件",
  "Attach files": "添加文件",
  "Attach files or images": "添加文件或图片",
  "Track this work as a Topic": "将此工作记录为协作事项",
  "Submitting answer": "正在提交回答",
  "Answer queued": "回答已排队",
  "Sending to thread": "正在发送到 Thread",
  "Sent to thread": "已发送到 Thread",
  "Send failed · draft restored": "发送失败 · 草稿已恢复",
  "Enter to send · Shift+Enter for new line": "Enter 发送 · Shift+Enter 换行",
  "stop current turn": "停止当前执行",
  "Copy message": "复制消息",
  "Reasoning process": "推理过程",
  "Token usage details": "Token 用量详情",
  "No messages yet": "还没有消息",
  "No requests need your input.": "目前没有需要你处理的请求。",
  "No topics yet.": "还没有协作事项。",
  "No schedules yet.": "还没有定时任务。",
  "No messages yet.": "还没有消息。",
  "No external identities yet.": "还没有外部身份。",
  "No external identities": "还没有外部身份",
  "No conversations yet.": "还没有外部会话。",
  "No connections yet.": "还没有外部连接。",
  "Manage external roles": "管理外部角色",
  "Add integration": "添加集成",
  "External messaging": "外部消息",
  "Connector operation": "连接器运行",
  "Open GitHub": "打开 GitHub",
  "Create new": "新建",
  "Use existing": "使用已有身份",
  "Choose a conversation": "选择会话",
  "External identity": "外部身份",
  "Connect Feishu": "连接飞书",
  "Connect Slack": "连接 Slack",
  "Connect Parall": "连接 Parall",
  "Connect your Feishu app": "连接你的飞书应用",
  "Connect your Slack app": "连接你的 Slack 应用",
  "Connect your Parall organization": "连接你的 Parall 组织",
  "Agents and external identities": "Agents 与外部身份",
  "Agent Addresses": "Agent 地址",
  "Advanced configuration": "高级配置",
  "Advanced settings": "高级设置",
  "App ID": "App ID",
  "App Secret": "App Secret",
  "App token": "App Token",
  "Bot token": "Bot Token",
  "Organization ID": "组织 ID",
  "Owner API key": "Owner API Key",
  "Parall API URL": "Parall API 地址",
  "Gateway": "网关",
  "Technical identity mapping": "技术身份映射",
  "Native connection, managed by CodexLoom.": "由 CodexLoom 管理的原生连接。",
  "Socket Mode, managed by CodexLoom.": "由 CodexLoom 管理的 Socket Mode。",
  "External identity and WebSocket, managed by Loom.": "由 Loom 管理的外部身份与 WebSocket。",
  "Which Agent speaks through Feishu?": "由哪个 Agent 通过飞书发言？",
  "Which Agent speaks through Slack?": "由哪个 Agent 通过 Slack 发言？",
  "Which Loom Agent speaks through Parall?": "由哪个 Loom Agent 通过 Parall 发言？",
  "Choose an Agent": "选择 Agent",
  "Choose a Parall Agent": "选择 Parall Agent",
  "External display name": "外部显示名称",
  "Where may it work?": "它可以在哪里工作？",
  "When should it respond?": "它应该何时回应？",
  "How should it reply?": "它应该如何回复？",
  "Who may send direct messages?": "谁可以发送私信？",
  "Can it initiate?": "它可以主动发言吗？",
  "Messages are routed to": "消息将转交给",
  "Dispatches for": "派发对象",
  "Direct messages": "私信",
  "Direct messages only": "仅私信",
  "Every message": "每条消息",
  "When mentioned": "被提及时",
  "Explicit dispatch": "明确派发",
  "Explicit dispatch only": "仅明确派发",
  "Send final answer": "发送最终答复",
  "Replies only": "仅回复",
  "Proactive + replies": "可主动发言并回复",
  "Do not reply": "不要回复",
  "No outbound messages": "不发送外部消息",
  "Anyone": "任何人",
  "No one": "任何人都不允许",
  "Allowlist only": "仅允许名单",
  "Only configured people": "仅已配置人员",
  "Every DM from this person": "此人的每条私信",
  "Only explicit replies": "仅明确要求的回复",
  "Apply policy": "应用策略",
  "Enable after saving": "保存后启用",
  "Verify and continue": "验证并继续",
  "Verify Owner and continue": "验证 Owner 并继续",
  "Check again": "重新检查",
  "Checking Feishu on this Mac…": "正在这台 Mac 上检查飞书…",
  "Checking Slack on this Mac…": "正在这台 Mac 上检查 Slack…",
  "Checking Parall…": "正在检查 Parall…",
  "Open Slack permissions": "打开 Slack 权限设置",
  "Allow Loom to discover channels": "允许 Loom 发现频道",
  "Invite the bot to a channel, then refresh.": "邀请机器人加入频道，然后刷新。",
  "Add this bot to a Feishu group, then refresh the list.": "将机器人加入飞书群，然后刷新列表。",
  "No active conversations found.": "没有找到活跃会话。",
  "No addresses": "没有地址",
  "No channels visible": "没有可见频道",
  "No groups visible": "没有可见群组",
  "No channels added. Channel messages are blocked.": "尚未添加频道，频道消息将被阻止。",
  "No groups added. Group messages are blocked.": "尚未添加群组，群组消息将被阻止。",
  "No joined group conversations discovered yet. Invite this Parall identity to a group; it will appear here automatically.": "尚未发现已加入的群聊。邀请这个 Parall 身份加入群聊后，它会自动出现在这里。",
  "No DM contacts have been seen. In managed mode, a new sender appears here as an access request and does not trigger the Agent.": "尚未发现私信联系人。在托管模式下，新联系人会作为访问请求出现在这里，不会直接触发 Agent。",
  "These instructions accompany dispatches from this conversation.": "这些指引会随该会话的任务一起发送。",
  "These instructions accompany messages from this channel.": "这些指引会随该频道的消息一起发送。",
  "These instructions are added whenever this group contacts the Agent.": "每当该群组联系 Agent 时，都会附加这些指引。",
  "What is this conversation for?": "这个会话用于什么？",
  "What is this channel for?": "这个频道用于什么？",
  "What is this group for?": "这个群组用于什么？",
  "What is this relationship for?": "这段关系用于什么？",
  "What should the Agent do here?": "Agent 在这里应该做什么？",
  "What should the Agent do for this person?": "Agent 应该为此人做什么？",
  "Anything it should avoid or remember?": "有哪些事项需要避免或牢记？",
  "Settings and maintenance": "设置与维护",
  "Create backup": "创建备份",
  "Restart CodexLoom": "重启 CodexLoom",
  "Check for updates": "检查更新",
  "Light": "浅色",
  "Dark": "深色",
  "System": "跟随系统",
  "Organization map": "组织关系图",
  "Collaboration map": "协作关系图",
  "Activity map": "活动关系图",
  "Agent directory": "Agent 名录",
  "Token: prompt + output": "Token：输入 + 输出",
  "Inspect operation, capacity, and Codex usage when you need them.": "按需检查运行状态、容量与 Codex 用量。",
  "Executing Agents": "正在执行的 Agents",
  "Owner Attention": "Owner 待处理",
  "Team Health": "团队健康状态",
  "No Agent is executing a Turn right now.": "当前没有 Agent 正在执行 Turn。",
  "No current capability issue.": "当前没有能力异常。",
  "Low-frequency CodexLoom operation and recovery.": "CodexLoom 的低频运维与恢复。",
  "Local backup": "本地备份",
  "GitHub triggers": "GitHub 触发器",
  "Restart Loom": "重启 Loom",
  "Copy code": "复制代码",
  "Waiting for GitHub authorization": "等待 GitHub 授权",
  "Temporary polling failure. Retrying automatically.": "临时轮询失败，正在自动重试。",
  "Observe pull requests and workflow runs without keeping a Turn or terminal watcher alive.": "无需保持 Turn 或终端监视器运行，即可观察 Pull Request 和工作流运行。",
  "Agents can keep working until they explicitly need a decision, fact, or authorization.": "Agents 可以持续工作，直到明确需要你的决定、事实或授权。",
  "Select a request": "选择一个请求",
  "Review its context before answering.": "回答前请先检查它的上下文。",
  "Waiting on this answer": "正在等待此回答",
  "Your answer": "你的回答",
  "Your answer is queued safely if the Agent is busy, then resumes this same Thread.": "如果 Agent 正忙，你的回答会安全排队，随后在同一 Thread 中继续。",
  "This request was dismissed without an answer.": "此请求已在未回答的情况下忽略。",
  "Create the smallest shared record needed to recover work across Turns, waiting periods, and Agent handoffs.": "只创建在跨 Turn、等待期和 Agent 交接中恢复工作所需的最小共享记录。",
  "Shared coordination across Agent work": "跨 Agent 工作的共享协调",
  "Track this as a Topic": "记录为协作事项",
  "Track work that must survive multiple Turns, waiting periods, or Agent handoffs.": "记录必须跨多个 Turn、等待期或 Agent 交接持续存在的工作。",
  "Brief history": "简要历史",
  "Evidence anchors": "证据锚点",
  "Latest update": "最新进展",
  "Limits and uncertainty": "限制与不确定性",
  "Link an evidence anchor": "关联证据锚点",
  "Link evidence": "关联证据",
  "No Topics in this view": "此视图中没有协作事项",
  "No evidence anchors linked.": "尚未关联证据锚点。",
  "No external waiting condition.": "没有外部等待条件。",
  "People and current work": "参与人员与当前工作",
  "Topics workspace": "协作事项工作区",
  "Topics list": "协作事项列表",
  "Topic detail": "协作事项详情",
  "Topic detail views": "协作事项详情视图",
  "Track a new Topic": "新建协作事项",
  "Back to Topics": "返回协作事项",
  "For you": "待你处理",
  waiting: "等待中",
  resolved: "已解决",
  all: "全部",
  current: "当前",
  history: "历史",
  Now: "当前进展",
  now: "刚刚",
  "result ready": "结果已就绪",
  "Result ready": "结果已就绪",
  "brief v": "简报 v",
  "· brief v": "· 简报 v",
  "· Topic v": "· 协作事项 v",
  "1 responsible ·": "1 个负责人 ·",
  participants: "个参与者",
  "versions · newest first": "个版本 · 最新优先",
  "Audit log ·": "审计日志 ·",
  "No shared brief yet.": "还没有共享简报。",
  "No summary recorded.": "尚未记录摘要。",
  "The Responsible Agent has not recorded a next step.": "负责人 Agent 尚未记录下一步。",
  "Complete when": "完成条件",
  "Owns the shared brief, routing, waiting conditions, and final close.": "负责共享简报、任务分派、等待条件及最终关闭。",
  Participant: "参与者",
  "Active Topic Turn": "正在执行的协作事项 Turn",
  Guide: "指导",
  Interrupt: "中断",
  "Select a Topic": "选择一个协作事项",
  "Recover the shared state without joining every Agent Thread.": "无需进入每个 Agent Thread 即可恢复共享状态。",
  "Create Topic": "创建协作事项",
  Title: "标题",
  "A bounded stage with a clear finish": "一个有明确完成边界的阶段",
  "Responsible Agent": "负责人 Agent",
  "Select the Agent accountable for the whole": "选择对整体工作负责的 Agent",
  "Why this work needs continuity": "说明这项工作为何需要持续跟进",
  "The observable boundary that closes this Topic": "描述可以关闭此协作事项的可验证条件",
  "Current brief (optional)": "当前简报（可选）",
  "What is already known now; not a full history import": "记录当前已知信息，无需导入完整历史",
  "Topic-scoped responsibility": "在此协作事项中的职责",
  "Remove participant": "移除参与者",
  "Object type": "对象类型",
  "Stable ID": "稳定 ID",
  Label: "标签",
  "Use a stable object ID. Do not copy an entire Agent Thread into the Topic.": "请使用稳定的对象 ID，不要把整个 Agent Thread 复制到协作事项中。",
  "message, turn, trigger, artifact, pr": "消息、Turn、触发器、产物、PR",
  "Guide active Turn": "指导正在执行的 Turn",
  "Interrupt active Turn": "中断正在执行的 Turn",
  "Reason / expected impact": "原因／预期影响",
  Reason: "原因",
  "Interrupt Turn": "中断 Turn",
  "Send guidance": "发送指导",
  "This acts on": "该操作作用于",
  "'s exact Turn": " 的指定 Turn",
  ". The Topic itself remains unchanged and the Responsible Agent is informed.": "。协作事项本身不会改变，并会通知负责人 Agent。",
  "Send Topic input to responsible Agent": "向负责人 Agent 发送协作事项输入",
  "Waiting for": "等待条件",
  since: "始于",
  "Resume check": "恢复检查",
  "Limits at this version": "此版本的限制",
  "Next at this version": "此版本的下一步",
  "State at this version": "此版本的状态",
  "Audit log": "审计日志",
  events: "事件",
  "Switch to English": "切换到英文",
  "Active agents": "活跃 Agents",
  "Agent workspace sidebar": "Agent 工作区侧栏",
  "Set a Goal": "设置目标",
  "Start long-running work": "开始长期任务",
  "send task": "发送任务",
  "task message": "任务消息",
  "Participants (optional)": "参与者（可选）",
  "Select an Agent": "选择 Agent",
  "Agent Inbox": "Agent 收件箱",
  "Agent Inspector": "Agent 检查器",
  "Collaboration Profile": "协作档案",
  "Thinking Effort": "推理强度",
  "Approval Policy": "审批策略",
  "Open workspace": "打开工作区",
  "Current context": "当前上下文",
  "View context": "查看上下文",
  "Thread Goal": "Thread 目标",
  "Thread token usage": "Thread Token 用量",
  "Token budget": "Token 预算",
  "No Thread usage yet": "还没有 Thread 用量数据",
  "Usage appears after this Agent completes a model call.": "Agent 完成一次模型调用后将显示用量。",
  "No declared Team relationships.": "尚未声明团队关系。",
  "No external addresses.": "没有外部地址。",
  "No managed conversations": "没有托管会话",
  "No scheduled times target this Agent.": "没有针对该 Agent 的定时任务。",
  "This Agent is not waiting on an external condition.": "该 Agent 当前没有等待外部条件。",
  "External conditions": "外部条件",
  "Scheduled times": "定时时间",
  "New trigger": "新建触发器",
  "Wake when": "唤醒条件",
  "First action after wake": "唤醒后的第一个动作",
  "GitHub source": "GitHub 数据源",
  "Pull request": "Pull Request",
  "Workflow run": "工作流运行",
  "Expected HEAD": "预期 HEAD",
  "Auto-select by Resource Owner": "按资源 Owner 自动选择",
  "Config can be changed after this turn finishes.": "本轮执行结束后可以修改配置。",
  "Connect GitHub in Settings before arming an external condition.": "启用外部条件前，请先在设置中连接 GitHub。",
};

const UI_TEXT_EN = Object.fromEntries(Object.entries(UI_TEXT_ZH).map(([english, chinese]) => [chinese, english]));
const PRESERVE_SELECTOR = "pre, code, [data-i18n-preserve]";
const TRANSLATED_ATTRIBUTES = ["placeholder", "title", "aria-label"] as const;

function replaceTrimmed(value: string, replacement: string): string {
  const start = value.search(/\S/);
  if (start < 0) return value;
  const end = value.search(/\s*$/);
  return `${value.slice(0, start)}${replacement}${value.slice(end)}`;
}

function translatePattern(value: string, language: AppLanguage): string | null {
  const patterns: Array<[RegExp, (...matches: string[]) => string]> = language === "zh-CN"
    ? [
        [/^(\d+) agents$/, (_, count) => `${count} 个 Agent`],
        [/^(\d+) active$/, (_, count) => `${count} 个活跃`],
        [/^(\d+) idle$/, (_, count) => `${count} 个空闲`],
        [/^(\d+) interrupted$/, (_, count) => `${count} 个已中断`],
        [/^(\d+) open$/, (_, count) => `${count} 个待处理`],
        [/^About (.+)$/, (_, name) => `关于 ${name}`],
        [/^Answer (.+)…$/, (_, name) => `回答 ${name}…`],
        [/^Send a task to (.+)…$/, (_, name) => `向 ${name} 发送任务…`],
        [/^Uploading (\d+) attachments?$/, (_, count) => `正在上传 ${count} 个附件`],
        [/^(\d+) identities · (\d+) conversation roles · (\d+) connected$/, (_, identities, roles, connected) => `${identities} 个身份 · ${roles} 个会话角色 · ${connected} 个已连接`],
        [/^(\d+) ready or unavailable$/, (_, count) => `${count} 个就绪或不可用`],
        [/^(\d+) active Agents · (\d+)m execution · (\d+) tokens · (\d+) Turns$/, (_, agents, minutes, tokens, turns) => `${agents} 个活跃 Agent · 执行 ${minutes} 分钟 · ${tokens} Tokens · ${turns} Turns`],
        [/^(\d+) inactive · (\d+)\/(\d+) tracked · (.+)$/, (_, inactive, tracked, total, timezone) => `${inactive} 个非活跃 · 已跟踪 ${tracked}/${total} · ${timezone}`],
        [/^(\d+) responsible · (\d+) participants$/, (_, responsible, participants) => `${responsible} 个负责人 · ${participants} 个参与者`],
        [/^brief v(\d+) · Topic v(\d+)$/, (_, brief, topic) => `简报 v${brief} · 协作事项 v${topic}`],
        [/^brief v(\d+) · (.+)$/, (_, brief, date) => `简报 v${brief} · ${date}`],
        [/^history (\d+)$/, (_, count) => `历史 ${count}`],
        [/^(\d+) versions · newest first$/, (_, count) => `${count} 个版本 · 最新优先`],
        [/^Audit log · (\d+) events$/, (_, count) => `审计日志 · ${count} 个事件`],
        [/^Continue this Topic with (.+)…$/, (_, agent) => `与 ${agent} 继续此协作事项…`],
        [/^Waiting for (.+)$/, (_, condition) => `等待 ${condition}`],
        [/^since (.+)$/, (_, date) => `始于 ${date}`],
        [/^Archive (.+)$/, (_, name) => `归档 ${name}`],
        [/^Close (.+) tab$/, (_, name) => `关闭 ${name} 标签页`],
        [/^(\d+)m$/, (_, count) => `${count} 分钟前`],
        [/^(\d+)h$/, (_, count) => `${count} 小时前`],
        [/^(\d+)d$/, (_, count) => `${count} 天前`],
      ]
    : [
        [/^(\d+) 个 Agent$/, (_, count) => `${count} agents`],
        [/^(\d+) 个活跃$/, (_, count) => `${count} active`],
        [/^(\d+) 个空闲$/, (_, count) => `${count} idle`],
        [/^(\d+) 个已中断$/, (_, count) => `${count} interrupted`],
        [/^(\d+) 个待处理$/, (_, count) => `${count} open`],
        [/^关于 (.+)$/, (_, name) => `About ${name}`],
        [/^回答 (.+)…$/, (_, name) => `Answer ${name}…`],
        [/^向 (.+) 发送任务…$/, (_, name) => `Send a task to ${name}…`],
        [/^正在上传 (\d+) 个附件$/, (_, count) => `Uploading ${count} attachments`],
        [/^(\d+) 个身份 · (\d+) 个会话角色 · (\d+) 个已连接$/, (_, identities, roles, connected) => `${identities} identities · ${roles} conversation roles · ${connected} connected`],
        [/^(\d+) 个就绪或不可用$/, (_, count) => `${count} ready or unavailable`],
        [/^(\d+) 个活跃 Agent · 执行 (\d+) 分钟 · (\d+) Tokens · (\d+) Turns$/, (_, agents, minutes, tokens, turns) => `${agents} active Agents · ${minutes}m execution · ${tokens} tokens · ${turns} Turns`],
        [/^(\d+) 个非活跃 · 已跟踪 (\d+)\/(\d+) · (.+)$/, (_, inactive, tracked, total, timezone) => `${inactive} inactive · ${tracked}/${total} tracked · ${timezone}`],
        [/^(\d+) 个负责人 · (\d+) 个参与者$/, (_, responsible, participants) => `${responsible} responsible · ${participants} participants`],
        [/^简报 v(\d+) · 协作事项 v(\d+)$/, (_, brief, topic) => `brief v${brief} · Topic v${topic}`],
        [/^简报 v(\d+) · (.+)$/, (_, brief, date) => `brief v${brief} · ${date}`],
        [/^历史 (\d+)$/, (_, count) => `history ${count}`],
        [/^(\d+) 个版本 · 最新优先$/, (_, count) => `${count} versions · newest first`],
        [/^审计日志 · (\d+) 个事件$/, (_, count) => `Audit log · ${count} events`],
        [/^与 (.+) 继续此协作事项…$/, (_, agent) => `Continue this Topic with ${agent}…`],
        [/^等待 (.+)$/, (_, condition) => `Waiting for ${condition}`],
        [/^始于 (.+)$/, (_, date) => `since ${date}`],
        [/^归档 (.+)$/, (_, name) => `Archive ${name}`],
        [/^关闭 (.+) 标签页$/, (_, name) => `Close ${name} tab`],
        [/^(\d+) 分钟前$/, (_, count) => `${count}m`],
        [/^(\d+) 小时前$/, (_, count) => `${count}h`],
        [/^(\d+) 天前$/, (_, count) => `${count}d`],
      ];

  for (const [pattern, formatter] of patterns) {
    const match = value.match(pattern);
    if (match) return formatter(...match);
  }
  return null;
}

export function translateUiText(value: string, language: AppLanguage): string {
  const trimmed = value.trim();
  if (!trimmed) return value;
  const exact = language === "zh-CN" ? UI_TEXT_ZH[trimmed] : UI_TEXT_EN[trimmed];
  const translated = exact || translatePattern(trimmed, language);
  return translated ? replaceTrimmed(value, translated) : value;
}

function isPreserved(element: Element | null): boolean {
  return Boolean(element?.closest(PRESERVE_SELECTOR));
}

function localizeElement(element: Element, language: AppLanguage) {
  if (isPreserved(element)) return;
  for (const attribute of TRANSLATED_ATTRIBUTES) {
    const current = element.getAttribute(attribute);
    if (!current) continue;
    const translated = translateUiText(current, language);
    if (translated !== current) element.setAttribute(attribute, translated);
  }
}

export function localizeUi(root: ParentNode, language = normalizeLanguage(i18n.resolvedLanguage || i18n.language)) {
  if (root instanceof Element) localizeElement(root, language);
  root.querySelectorAll?.("*").forEach((element) => localizeElement(element, language));

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) {
    if (!isPreserved(node.parentElement)) {
      const current = node.nodeValue || "";
      const translated = translateUiText(current, language);
      if (translated !== current) node.nodeValue = translated;
    }
    node = walker.nextNode();
  }
}

export function installUiLocalization(): () => void {
  let frame = 0;
  const apply = () => {
    frame = 0;
    if (document.body) localizeUi(document.body);
  };
  const schedule = () => {
    if (!frame) frame = window.requestAnimationFrame(apply);
  };
  const observer = new MutationObserver(schedule);
  observer.observe(document.documentElement, {
    subtree: true,
    childList: true,
    characterData: true,
    attributes: true,
    attributeFilter: [...TRANSLATED_ATTRIBUTES],
  });
  i18n.on("languageChanged", schedule);
  schedule();

  return () => {
    if (frame) window.cancelAnimationFrame(frame);
    observer.disconnect();
    i18n.off("languageChanged", schedule);
  };
}
